### ISSUE TITLE
Create an Account

### ISSUE THREAD

**Issue by alexsenden** [alexsenden/harmony#10]
Relates to feature: #3 

As a new user, I want to create an account so that I can interact with post

Acceptance Criteria: 
Given that I am in the role of an unregistered user
When I open the webpage
Then the system shows me a Login or Register button
When I click on the button
Then the system shows me a page where I can login or register
When I fill in the required details (email, username, password)
And I click the “Register” button or press enter on the keyboard
Then the system stores my information and logs me in

**Comment by Dankgen** [comment]
Added in #55
