### ISSUE TITLE
Sign in to an Account

### ISSUE THREAD

**Issue by alexsenden** [alexsenden/harmony#12]
Relates to feature #3 

As an existing user, I want to sign in to my account so that I can interact with posts

Acceptance Criteria: 
Given that I am in the role of an existing user
When I open the webpage
Then the system shows me a Login or Register button
When I click on the button
Then the system shows me a page where I can login or register
When I fill in the required details (email, username, password)
And I click the “Login” button or press enter on the keyboard
The system ensures my credentials are correct and logs me in

**Comment by Dankgen** [comment]
Added in #55
