### ISSUE TITLE
Follow Other Users

### ISSUE THREAD

**Issue by alexsenden** [alexsenden/harmony#20]
Relates to feature #6 

As a logged-in user, I want to follow other users so that I can stay up to date with their recent content

Acceptance Criteria:
Given that I am in the role of a logged in user
When I open the “Home” page
Then the system shows me a series of posts
When I click the desired post
The system shows me a pop up including the users profile username/image
When I click the username/image
The system shows me the users profile page with a follow button
When I click the follow button
The system will update to show that I have followed that user

**Comment by Dankgen** [comment]
Finished in #61
